---
    language: python
    services: docker
    
    env:
      global:
        - MOLECULE_PROJECT_DIR: "$TRAVIS_BUILD_DIR"
        - MOLECULE_ROLE_NAME: "$(basename $TRAVIS_BUILD_DIR)"
        - HCLOUD_TOKEN: "$HCLOUD_TOKEN"
    
    before_script:
      - wget https://raw.githubusercontent.com/nl2go/docker-molecule/2.22-n2g-1.0.0/requirements.txt
      - wget https://raw.githubusercontent.com/nl2go/docker-molecule/2.22-n2g-1.0.0/docker-compose.yml
      - docker-compose up -d
      - docker-compose exec molecule pip install dnspython requests==2.20.1 docker docker-compose hcloud molecule[hetznercloud]
      - docker-compose exec molecule pip install git+https://github.com/pycontribs/molecule-hetznercloud.git@master#egg=molecule-hetznercloud
    
    script:
      - docker-compose exec molecule molecule test --all
    
    after_script:
      - docker-compose down
      - codecov
    
    notifications:
      webhooks: https://galaxy.ansible.com/api/v1/notifications/