---
- name: Get physical network device
  shell: |
    set -o pipefail
    ip route get 8.8.8.8 | awk '{print $5 }'
  args:
    executable: /bin/bash
  register: network_device_cmd
  changed_when: network_device_cmd.stderr | length > 0

- name: Set network device variable
  set_fact:
    hetzner_failover_keepalived_physical_device: "{{ network_device_cmd.stdout }}"

- name: Set failover vswitch interface name
  set_fact:
    hetzner_failover_keepalived_track_device: "{{ hetzner_failover_keepalived_physical_device }}.{{ hetzner_failover_keepalived_vswich_id }}"

- name: Define additional routing table that will handle new rules and routes
  lineinfile:
    path: /etc/iproute2/rt_tables
    regexp: '^1 vswitch'
    line: 1 vswitch

- name: Make sure ip-up and if-down hooks directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - /etc/network/if-up.d
    - /etc/network/if-down.d

- name: Copy across interfaces if-up hook scripts
  template:
    src: if-up.j2
    dest: /etc/network/if-up.d/z90-{{ hetzner_failover_keepalived_physical_device }}
    owner: root
    group: root
    mode: 0755
  notify: Restart vswitch network interface

- name: Copy across interfaces if-down hook scripts
  template:
    src: if-down.j2
    dest: /etc/network/if-down.d/z90-{{ hetzner_failover_keepalived_physical_device }}
    owner: root
    group: root
    mode: 0755
  notify: Restart vswitch network interface

- name: Copy across dummy interface settings
  template:
    src: dummy-iface.j2
    dest: /etc/network/interfaces.d/dummy0
    owner: root
    group: root
    mode: 0644

- name: Set default keepalived priority
  set_fact:
    hetzner_failover_keepalived_priority: 50

- name: Overwrite keepalived priority when master
  set_fact:
    hetzner_failover_keepalived_priority: 100
  when: hetzner_failover_keepalived_state == 'MASTER'

- name: Copy across keepalived configuration file
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart keepalived

- name: Copy across keepalived notify script
  template:
    src: keepalived_notify.sh.j2
    dest: /usr/local/bin//keepalived_notify.sh
    owner: root
    group: root
    mode: 0755

- name: Flush handlers as keepalived needs proper network settings in order to started
  meta: flush_handlers

- name: Ensure keepalived is started and enabled on boot
  service:
    name: keepalived
    state: started
    enabled: yes
