---
  - name: Restart keepalived
    service:
      name: keepalived
      state: restarted

  - name: Restart vswitch network interface
    include_tasks: restart_track_device.yml

  - name: Restart dummy network interface
    include_tasks: restart_dummy_device.yml