---
  scenario:
    test_sequence:
      - lint
      - cleanup
      - destroy
      - dependency
      - syntax
      - create
      - prepare
      - converge
      # - idempotence # cuurently checks if service is running but that does not work in docker
      - side_effect
      - verify
      - cleanup
      - destroy
  driver:
    name: docker
  lint:
    name: yamllint
  platforms:
    - name: debian9
      image: debian:9
      dockerfile: ../resources/Dockerfile.j2
      capabilities:
        - NET_ADMIN
      groups:
        - platforms
    - name: debian10
      image: debian:10
      dockerfile: ../resources/Dockerfile.j2
      capabilities:
        - NET_ADMIN
      groups:
        - platforms
    - name: Ubuntu16
      image: ubuntu:16.04
      dockerfile: ../resources/Dockerfile.j2
      capabilities:
        - NET_ADMIN
      groups:
        - platforms
    - name: Ubuntu18
      image: ubuntu:18.04
      dockerfile: ../resources/Dockerfile.j2
      capabilities:
        - NET_ADMIN
      groups:
        - platforms
  provisioner:
    name: ansible
    inventory:
      group_vars:
        all:
          hetzner_vswitch_webservice_base_url: http://hetzner-robot:3000
          hetzner_vswitch_webservice_username: robot
          hetzner_vswitch_webservice_password: secret
          hetzner_vswitch_webservice_mock: nl2go/hetzner-robot-api-mock:1.2.3
    lint:
      name: ansible-lint
    playbooks:
      prepare: ../resources/playbooks/prepare.yml
      cleanup: ../resources/playbooks/cleanup.yml
  verifier:
    name: testinfra
    env:
      HETZNER_ROBOT_BASE_URL: http://hetzner-robot:3000
    lint:
      name: flake8
