---
- name: Converge
  hosts: all
  roles:
    - role: nl2go.hetzner_vswitch
    - role: ansible-role-hetzner-failover
  vars:
    hetzner_vswitch_instances:
      - name: failover
        vlan: 4023
        ipv4_address: 192.168.200.0
        ipv4_netmask: 255.255.255.0
    hetzner_vswitch_host:
      - name: failover
        ipv4_address: 192.168.200.1
    hetzner_failover_keepalived_state: MASTER
    hetzner_failover_keepalived_vswitch_ip: 192.168.200.1
    hetzner_failover_keepalived_peer_ip: 192.168.200.2
    hetzner_failover_keepalived_virtual_router_id: 42
    hetzner_failover_keepalived_public_ipaddress: 154.222.4.34
    hetzner_failover_keepalived_public_network_prefix: 29
    hetzner_failover_keepalived_public_default_gateway: 154.222.4.33
    keepalived_failover_private_ipaddress: 192.168.200.250
    keepalived_failover_private_network_prefix: 24
    keepalived_failover_private_default_gateway: 192.168.200.1
    hetzner_failover_keepalived_auth_pass: X98a8378gdDDdS
    hetzner_failover_keepalived_vswich_id: 4023
