---
- name: Remove Hetzner Robot Mock API
  hosts: localhost
  tasks:
    - name: Stop Hetzner Robot Mock API instance
      nl2go_hcloud_server:
        api_token: "{{ lookup('env','HCLOUD_TOKEN') }}"
        name: hetzner-robot
        server_type: cx11
        location: nbg1
        image: "{{ hetzner_robot_mock_service_hcloud_image_id }}"
        state: absent