---
- name: Determine Hetzner Robot Mock API URL
  hosts: all
  tasks:
    - name: Check Hetzner Robot Mock API instance
      nl2go_hcloud_server:
        api_token: "{{ lookup('env','HCLOUD_TOKEN') }}"
        name: hetzner-robot
        server_type: cx11
        location: nbg1
        image: "{{ hetzner_robot_mock_service_hcloud_image_id }}"
        state: present
      register: mock_server_result
      delegate_to: localhost
      run_once: yes

    - name: Set URL of Hetzner Robot Mock API service
      set_fact:
        hetzner_vswitch_webservice_base_url: http://{{ mock_server_result.nl2go_hcloud_server.ipv4_address }}:3000

- name: Converge
  hosts: all
  roles:
    - role: nl2go.hetzner_vswitch
    - role: ansible-role-hetzner-failover
  vars:
    hetzner_vswitch_instances:
      - name: failover
        vlan: 4023
        ipv4_address: 192.168.200.0
        ipv4_netmask: 255.255.255.0
    hetzner_failover_keepalived_public_virtual_router_id: 42
    hetzner_failover_keepalived_public_ipaddress: 154.222.4.34
    hetzner_failover_keepalived_public_network_prefix: 29
    hetzner_failover_keepalived_public_default_gateway: 154.222.4.33
    hetzner_failover_keepalived_private_virtual_router_id: 84
    hetzner_failover_keepalived_private_ipaddress: 192.168.200.250
    hetzner_failover_keepalived_private_network_prefix: 24
    hetzner_failover_keepalived_private_default_gateway: 192.168.200.1
    hetzner_failover_keepalived_auth_pass: X98a8378gdDDdS
    hetzner_failover_keepalived_vswich_id: 4023
